### импортируем библиотеки

In [1]:
import os
import pandas as pd

### обработка файла

In [2]:
COLUMNS = ["x1", "Реестровый номер контракта", "x2", "x3", "x4", "x5",
                      "x6", "x7", "x8", "x9", "x10", "x11", "x12",
                      "date1", "date2", "date3", "date4", "date5", "date6", "x13", "x14",
                      "x15", "x16", "x17", "x18", "y_description", "y"]
# пишем результат на диск
PATH = r"C:\Users\AnnaZheleznova\Documents\Cource_BigData\Diplom_github\Data" 
SEP = "___"

In [3]:
# датасет объемный, используем параметр chinksize, делим на строки
chunksize = 10 ** 6
i = 0
with pd.read_csv('C:\\Users\\AnnaZheleznova\\Documents\\Cource_BigData\\Diplom_github\\fz.zip', chunksize=chunksize, on_bad_lines="skip",dtype='unicode') as reader:
    for df in reader:
        if i < 3:
            i += 1
            continue

        df.columns = COLUMNS

        df["y"] = df["y"].astype(str)
        df = df[df["y"] != "<НЕ ОПРЕДЕЛЕНО>"]
        df = df[df["y"] != "<НЕ РАСПРЕДЕЛЕНО>"]
        df = df[df["y"].str.len() == 4]

        break

In [4]:
df["y"].unique()

array(['41.2', '43.3', '19.2', '21.1', '21.2', '22.1', '20.5', '86.9',
       '32.5', '17.1', '81.2', '71.2', '14.1', '80.1', '61.1', '60.1',
       '25.9', '33.1', '10.7', '10.3', '10.8', '27.5', '80.2', '96.0',
       '17.2', '10.5', '10.1', '31.0', '01.1', '01.2', '10.6', '28.2',
       '20.2', '36.0', '20.1', '25.7', '23.9', '27.4', '10.4', '10.2',
       '13.2', '58.1', '38.2', '01.4', '58.2', '24.1', '26.6', '26.5',
       '22.2', '13.9', '20.4', '38.1', '25.1', '28.1', '24.4', '23.4',
       '65.1', '35.2', '20.3', '32.9', '43.2', '26.3', '18.1', '56.2',
       '63.1', '26.2', '08.9', '95.1', '29.3', '46.1', '35.1', '35.3',
       '43.9', '26.4', '27.3', '61.9', '37.0', '71.1', '15.2', '85.4',
       '82.3', '46.5', '24.5', '25.2', '14.3', '28.9', '27.1', '27.9',
       '23.5', '23.6', '03.1', '28.3', '14.2', '15.1', '10.9', '11.0',
       '62.0', '63.9', '53.1', '84.2', '86.1', '68.2', '16.2', '61.2',
       '74.9', '73.2', '49.3', '53.2', '81.1', '46.3', '32.3', '69.2',
       '86.2', '42.1', '68.1', '45.2', '27.2', '90.0', '30.9', '13.1',
       '59.2', '33.2', '06.2', '26.7', '23.1', '24.3', '24.2', '82.1',
       '68.3', '47.5', '59.1', '52.2', '55.1', '73.1', '51.1', '47.7',
       '16.1', '84.1', '85.2', '41.1', '81.3', '79.1', '28.4', '47.4',
       '43.1', '52.1', '50.1', '61.3', '01.3', '29.1', '03.2', '08.1',
       '46.4', '42.2', '46.9', '49.5', '49.4', '75.0', '29.2', '82.9',
       '32.4', '02.2', '46.7', '26.1', '45.1', '23.3', '42.9', '46.6',
       '32.1', '74.3', '93.2', '45.3', '05.1', '47.6', '23.7', '77.3',
       '77.2', '79.9', '60.2', '56.1', '32.2', '95.2', '25.3', '77.1',
       '45.4', '74.2', '26.8', '85.3', '20.6', '02.3', '99.0', '47.3',
       '66.1', '64.9', '72.1', '93.1', '85.1', '25.4', '94.1', '64.1',
       '02.4', '55.9', '91.0', '70.2', '69.1', '66.2', '87.9', '06.1',
       '72.2', '70.1', '55.2', '74.1', '88.9', '49.1', '02.1', '51.2',
       '94.9', '25.6', '30.3', '09.1', '05.2', '47.2', '78.3', '82.2',
       '30.2', '01.7', '23.2', '77.4', '97.0', '13.3', '30.1', '64.2',
       '47.1', '12.0', '19.1', '46.2', '39.0', '18.2', '47.9', '88.1',
       '87.3', '87.2', '78.2', '47.8', '09.9', '87.1', '25.5', '01.6',
       '84.3', '98.1', '56.3', '50.3', '55.3', '65.2', '19.3', '49.2',
       '07.2', '78.1', '38.3', '30.4', '50.4', '50.2', '80.3', '92.2',
       '98.2', '07.1', '94.2'], dtype=object)

In [5]:
t = df[df["y"].str.len() == 4]
t["y"].unique()

array(['41.2', '43.3', '19.2', '21.1', '21.2', '22.1', '20.5', '86.9',
       '32.5', '17.1', '81.2', '71.2', '14.1', '80.1', '61.1', '60.1',
       '25.9', '33.1', '10.7', '10.3', '10.8', '27.5', '80.2', '96.0',
       '17.2', '10.5', '10.1', '31.0', '01.1', '01.2', '10.6', '28.2',
       '20.2', '36.0', '20.1', '25.7', '23.9', '27.4', '10.4', '10.2',
       '13.2', '58.1', '38.2', '01.4', '58.2', '24.1', '26.6', '26.5',
       '22.2', '13.9', '20.4', '38.1', '25.1', '28.1', '24.4', '23.4',
       '65.1', '35.2', '20.3', '32.9', '43.2', '26.3', '18.1', '56.2',
       '63.1', '26.2', '08.9', '95.1', '29.3', '46.1', '35.1', '35.3',
       '43.9', '26.4', '27.3', '61.9', '37.0', '71.1', '15.2', '85.4',
       '82.3', '46.5', '24.5', '25.2', '14.3', '28.9', '27.1', '27.9',
       '23.5', '23.6', '03.1', '28.3', '14.2', '15.1', '10.9', '11.0',
       '62.0', '63.9', '53.1', '84.2', '86.1', '68.2', '16.2', '61.2',
       '74.9', '73.2', '49.3', '53.2', '81.1', '46.3', '32.3', '69.2',
       '86.2', '42.1', '68.1', '45.2', '27.2', '90.0', '30.9', '13.1',
       '59.2', '33.2', '06.2', '26.7', '23.1', '24.3', '24.2', '82.1',
       '68.3', '47.5', '59.1', '52.2', '55.1', '73.1', '51.1', '47.7',
       '16.1', '84.1', '85.2', '41.1', '81.3', '79.1', '28.4', '47.4',
       '43.1', '52.1', '50.1', '61.3', '01.3', '29.1', '03.2', '08.1',
       '46.4', '42.2', '46.9', '49.5', '49.4', '75.0', '29.2', '82.9',
       '32.4', '02.2', '46.7', '26.1', '45.1', '23.3', '42.9', '46.6',
       '32.1', '74.3', '93.2', '45.3', '05.1', '47.6', '23.7', '77.3',
       '77.2', '79.9', '60.2', '56.1', '32.2', '95.2', '25.3', '77.1',
       '45.4', '74.2', '26.8', '85.3', '20.6', '02.3', '99.0', '47.3',
       '66.1', '64.9', '72.1', '93.1', '85.1', '25.4', '94.1', '64.1',
       '02.4', '55.9', '91.0', '70.2', '69.1', '66.2', '87.9', '06.1',
       '72.2', '70.1', '55.2', '74.1', '88.9', '49.1', '02.1', '51.2',
       '94.9', '25.6', '30.3', '09.1', '05.2', '47.2', '78.3', '82.2',
       '30.2', '01.7', '23.2', '77.4', '97.0', '13.3', '30.1', '64.2',
       '47.1', '12.0', '19.1', '46.2', '39.0', '18.2', '47.9', '88.1',
       '87.3', '87.2', '78.2', '47.8', '09.9', '87.1', '25.5', '01.6',
       '84.3', '98.1', '56.3', '50.3', '55.3', '65.2', '19.3', '49.2',
       '07.2', '78.1', '38.3', '30.4', '50.4', '50.2', '80.3', '92.2',
       '98.2', '07.1', '94.2'], dtype=object)

In [5]:
# обрабатываем и сохраняем данные в PATH, немного ждем результат
chunksize = 10 ** 5
chunk_id = 0
with pd.read_csv('C:\\Users\\AnnaZheleznova\\Documents\\Cource_BigData\\Diplom_github\\fz.zip', chunksize=chunksize, on_bad_lines="skip", dtype='unicode') as reader:
    for df in reader:
        print(chunk_id, end=", ")
        if chunk_id >= 0:
            df.columns = COLUMNS

            df["y"] = df["y"].astype(str)
            df = df[df["y"] != "<НЕ ОПРЕДЕЛЕНО>"]
            df = df[df["y"] != "<НЕ РАСПРЕДЕЛЕНО>"]
            df = df[df["y"].str.len() == 4]


            df = df[["x4", "x7", "x8", "x11", "x12", "x14", "x15", "y_description", "y"]]

            for y in df["y"].unique():
                if len(y) < 20:
                    df_crop = df[df["y"] == y]
                    df_crop.to_csv(os.path.join(PATH, f"{y}{SEP}{chunk_id}.csv"))
                else:
                    print()
                    print(y)

        chunk_id += 1

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292,

In [10]:
chunk_id

293

In [11]:
df["y"].unique()

array(['35.3', '26.5', '26.2', '28.2', '22.1', '22.2', '20.2', '20.4',
       '21.2', '80.1', '49.3', '32.5', '16.2', '17.2', '20.5', '32.9',
       '26.6', '68.1', '42.1', '19.2', '86.1', '85.1', '71.1', '43.9',
       '36.0', '37.0', '17.1', '53.2', '35.2', '58.1', '56.2', '43.2',
       '42.2', '35.1', '58.2', '01.1', '10.5', '10.6', '10.1', '01.4',
       '74.9', '61.2', '27.5', '26.3', '41.2', '86.9', '86.2', '49.4',
       '27.4', '23.6', '23.5', '20.3', '61.1', '27.3', '03.1', '28.9',
       '08.1', '87.9', '10.3', '01.2', '10.8', '14.1', '10.7', '27.9',
       '38.2', '81.1', '32.4', '62.0', '43.3', '53.1', '31.0', '47.7',
       '05.1', '10.2', '38.1', '25.7', '25.9', '29.2', '32.3', '23.1',
       '95.1', '13.9', '61.9', '42.9', '25.1', '10.9', '68.2', '28.3',
       '13.2', '06.2', '45.2', '26.4', '33.1', '25.3', '68.3', '59.1',
       '93.2', '71.2', '08.9', '15.2', '39.0', '55.9', '55.1', '29.1',
       '78.3', '21.1', '13.1', '85.4', '65.1', '64.9', '41.1', '10.4',
       '82.3', '29.3', '26.7', '52.1', '33.2', '27.2', '81.2', '63.9',
       '63.1', '56.1', '96.0', '20.6', '05.2', '24.1', '80.2', '47.5',
       '18.1', '13.3', '46.7', '24.2', '25.2', '20.1', '27.1', '81.3',
       '85.2', '28.1', '02.1', '84.2', '75.0', '46.4', '46.1', '52.2',
       '24.3', '43.1', '14.3', '72.2', '24.4', '85.3', '23.4', '16.1',
       '90.0', '02.2', '32.1', '32.2', '55.2', '30.9', '26.8', '95.2',
       '02.4', '60.2', '14.2', '15.1', '23.9', '49.2', '23.3', '24.5',
       '28.4', '82.9', '93.1', '73.2', '77.1', '79.9', '79.1', '91.0',
       '51.1', '30.3', '30.2', '66.2', '77.3', '30.1', '60.1', '01.3',
       '64.1', '49.5', '73.1', '11.0', '23.7', '94.9', '45.4', '82.2',
       '51.2', '77.2', '84.1', '72.1', '01.6', '26.1', '87.3', '88.9',
       '0.00', '94.1', '82.1', '47.1', '69.2', '70.2', '74.3', '61.3',
       '74.1', '47.6', '55.3', '38.3', '03.2', '47.4', '25.4', '74.2',
       '49.1', '25.6', '45.3', '47.3', '69.1', '78.2', '66.1', '46.9'],
      dtype=object)

## смотрим результат

In [12]:
df[df["y"] == "70.2"]

,x4,x7,x8,x11,x12,x14,x15,y_description,y
29215309,"ГКУ ПК \ЦБУ\""""","ГБУЗ \КМСЧ № 1\""""",Пермский край,"Оказание услуг по ведению бухгалтерского, нало...",\N,16636558.28,16636558.28,70.2,70.2
29218464,"ООО \СЕРВИС КУЛЬТУРНОЙ СТОЛИЦЫ\""""",ГБДОУ ДЕТСКИЙ САД № 23 КРАСНОГВАРДЕЙСКОГО РАЙО...,Город Санкт-Петербург город федерального значения,Оказание услуг по проведению оценки профессион...,\N,26400.00,3236.00,70.2,70.2
29219141,"ООО \РАЦИО\""""",ГБДОУ ДЕТСКИЙ САД №4 КРАСНОГВАРДЕЙСКОГО РАЙОНА...,Город Санкт-Петербург город федерального значения,Оказание услуг по проведению оценки профессион...,\N,34200.00,3132.00,70.2,70.2
29219488,"ООО \МЕТРОЛОГ\""""",ГБДОУ ДЕТСКИЙ САД № 24 КРАСНОГВАРДЕЙСКОГО РАЙ...,Город Санкт-Петербург город федерального значения,Оказание услуг по оценке профессиональных риск...,\N,25833.32,20020.67,70.2,70.2
29251363,ТПП Г. СОЧИ,АДМИНИСТРАЦИЯ ГОРОДА СОЧИ,Краснодарский край,Оказание поддержки субъектам малого и среднего...,местный бюджет,2149166.00,2149166.00,70.2,70.2
29258474,"ГКУ ПК \ЦБУ\""""","ГБУЗ ПК \ККД\""""",Пермский край,"Оказание услуг по ведению бухгалтерского, нало...",\N,11976184.12,11345858.64,70.2,70.2
29261344,"ООО \РАЦИО\""""",ГБДОУ ДЕТСКИЙ САД № 18 КРАСНОГВАРДЕЙСКОГО РАЙО...,Город Санкт-Петербург город федерального значения,Оказание услуг по оценке профессиональных риск...,\N,17550.00,1912.25,70.2,70.2